server:
  port: 8082
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  signerKey: cnf61zcey4yE0RfDwk3yOAgi+CRVsjb1LPQP0O9e0GyLworFq8IthDFERD/0bxy2
  valid-duration: 3600
  refreshable-duration: 86400

file:
  directory: ./uploads/
  max-size: 10MB

app:
  default-admin-id: d50f8589-da20-49e8-a3f3-6a115d1f68d7